In [1]:
import pandas as pd
import numpy as np

In [2]:
# This dataset is not included in github and can be found here: 
# https://www.kaggle.com/datasets/fabioturazzi/cryptocurrency-tweets-with-sentiment-analysis
tweets = pd.read_csv("tweets_sentiment.csv")

/Users/davidhackett/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
tweets.dtypes

Unnamed: 0           int64
id                 float64
conversation_id    float64
created_at          object
date                object
time                object
timezone             int64
user_id            float64
username            object
name                object
place               object
tweet               object
language            object
mentions            object
urls                object
photos              object
replies_count        int64
retweets_count       int64
likes_count          int64
hashtags            object
cashtags            object
link                object
retweet               bool
quote_url           object
video                int64
thumbnail           object
near               float64
geo                float64
source             float64
user_rt_id         float64
user_rt            float64
retweet_id         float64
reply_to            object
retweet_date       float64
translate          float64
trans_src          float64
trans_dest         float64
search              object
decoded_tweet       object
neg                float64
neu                float64
pos                float64
compound           float64
dtype: object

In [4]:
# eliminate unnecessary fields
tweets_filtered = tweets[['date', 'mentions', 'replies_count', 'retweets_count', 'likes_count', \
                          'hashtags', 'cashtags', 'neg', 'neu', 'pos', 'compound']]

In [5]:
tweets_filtered.sample(10)

,date,mentions,replies_count,retweets_count,likes_count,hashtags,cashtags,neg,neu,pos,compound
112651,2019-09-04,"[{'screen_name': 'lagarde', 'name': 'christine...",3,45,81,[],[],0.000,0.800,0.200,0.6705
447945,2018-05-23,[],3,2,48,"['neverforget', 'bitcoin']",[],0.227,0.773,0.000,-0.6597
387668,2017-01-11,[],1,13,25,[],[],0.066,0.934,0.000,-0.0900
151309,2020-12-23,"[{'screen_name': 'therealtimbos', 'name': 'tim...",2,22,85,['cryptocurrency'],['shr'],0.000,1.000,0.000,0.0000
621988,2021-01-23,[],38,4,146,['bitcoin'],[],0.116,0.704,0.180,0.5994
450120,2018-06-09,[],12,36,125,"['substratum', 'cryptocurrency', 'bitcoin', 'b...",[],0.000,0.868,0.132,0.4939
284854,2018-05-11,[],1,57,78,"['cryptfunder', 'cfnd', 'cryptocurrency', 'cry...",[],0.000,1.000,0.000,0.0000
772060,2018-03-28,[],2,8,31,"['xrpthestandard', 'xrp', 'ripple']",[],0.078,0.841,0.081,0.0258
709807,2019-01-17,"[{'screen_name': 'brcointelegraph', 'name': 'c...",1,41,192,"['brazil', 'usebnb', 'npxs', 'btc', 'eth']",[],0.000,1.000,0.000,0.0000
622519,2021-01-25,[],11,25,114,['bitcoin'],[],0.000,0.812,0.188,0.4019

In [6]:
len(tweets_filtered)

824908

In [7]:
bitcoin_tweets = tweets_filtered[tweets_filtered["hashtags"].str.contains("bitcoin|btc", regex=True)]

In [8]:
len(bitcoin_tweets)

294562

In [9]:
bitcoin_tweets.head()

,date,mentions,replies_count,retweets_count,likes_count,hashtags,cashtags,neg,neu,pos,compound
2,2013-04-14,[],15,153,61,['bitcoin'],[],0.000,1.000,0.000,0.0000
24,2014-01-02,"[{'screen_name': 'kanyewest', 'name': 'ye', 'i...",12,76,44,['bitcoin'],[],0.000,1.000,0.000,0.0000
59,2014-02-05,"[{'screen_name': 'brianeha', 'name': 'brian pa...",4,38,24,['bitcoin'],[],0.000,1.000,0.000,0.0000
66,2014-02-15,[],2,26,23,"['dogecoin', 'bitcoin']",[],0.121,0.879,0.000,-0.2960
75,2014-02-25,"[{'screen_name': 'fart', 'name': 'food truck d...",5,34,38,"['bitcoin', 'cryptocurrency']",[],0.176,0.707,0.116,-0.2942

In [12]:
bitcoin_tweets["compound_times_replies"] = bitcoin_tweets["compound"] * bitcoin_tweets["replies_count"]
bitcoin_tweets["compound_times_retweets"] = bitcoin_tweets["compound"] * bitcoin_tweets["retweets_count"]
bitcoin_tweets["compound_times_likes"] = bitcoin_tweets["compound"] * bitcoin_tweets["likes_count"]

<ipython-input-12-7fd0a1d70032>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bitcoin_tweets["compound_times_replies"] = bitcoin_tweets["compound"] * bitcoin_tweets["replies_count"]
<ipython-input-12-7fd0a1d70032>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bitcoin_tweets["compound_times_retweets"] = bitcoin_tweets["compound"] * bitcoin_tweets["retweets_count"]
<ipython-input-12-7fd0a1d70032>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bitcoin_tweets["compound_times_likes"] = bitcoin_tweets["compound"] * bitcoin_tweets["likes_count"]

In [13]:
bitcoin_tweets.head()

,date,mentions,replies_count,retweets_count,likes_count,hashtags,cashtags,neg,neu,pos,compound,compound_times_replies,compound_times_retweets,compound_times_likes
2,2013-04-14,[],15,153,61,['bitcoin'],[],0.000,1.000,0.000,0.0000,0.000,0.0000,0.0000
24,2014-01-02,"[{'screen_name': 'kanyewest', 'name': 'ye', 'i...",12,76,44,['bitcoin'],[],0.000,1.000,0.000,0.0000,0.000,0.0000,0.0000
59,2014-02-05,"[{'screen_name': 'brianeha', 'name': 'brian pa...",4,38,24,['bitcoin'],[],0.000,1.000,0.000,0.0000,0.000,0.0000,0.0000
66,2014-02-15,[],2,26,23,"['dogecoin', 'bitcoin']",[],0.121,0.879,0.000,-0.2960,-0.592,-7.6960,-6.8080
75,2014-02-25,"[{'screen_name': 'fart', 'name': 'food truck d...",5,34,38,"['bitcoin', 'cryptocurrency']",[],0.176,0.707,0.116,-0.2942,-1.471,-10.0028,-11.1796

In [14]:
bitcoin_pivot = bitcoin_tweets.pivot_table(index="date", \
                                           values=["cashtags", "replies_count", "retweets_count",\
                                                   "likes_count", "neg", "neu", "pos", "compound", \
                                                  "compound_times_replies","compound_times_likes", \
                                                   "compound_times_retweets"],
                                          aggfunc={"cashtags" : "count", "replies_count" : np.sum,\
                                                   "retweets_count": np.sum, "likes_count": np.sum,\
                                                   "neg": np.mean, "neu": np.mean, "pos": np.mean,\
                                                   "compound": np.mean,  "compound_times_replies": np.sum,\
                                                   "compound_times_likes": np.sum, "compound_times_retweets": np.sum})

In [26]:
bitcoin_pivot.rename(columns={'cashtags': "count"}, inplace=True)
bitcoin_pivot["compound_weighted_replies"] = bitcoin_pivot["compound_times_replies"] / bitcoin_pivot['replies_count']
bitcoin_pivot["compound_weighted_likes"] = bitcoin_pivot["compound_times_likes"] / bitcoin_pivot['likes_count']
bitcoin_pivot["compound_weighted_retweets"] = bitcoin_pivot["compound_times_retweets"] / bitcoin_pivot['retweets_count']

In [27]:
bitcoin_pivot.sample(10)

,count,compound,compound_times_likes,compound_times_replies,compound_times_retweets,likes_count,neg,neu,pos,replies_count,retweets_count,compound_weighted_replies,compound_weighted_likes,compound_weighted_retweets
date,,,,,,,,,,,,,,
2020-01-30,154,0.405682,6318.1959,2676.3137,2619.5726,13838,0.032838,0.829429,0.137721,5308,5587,0.504204,0.456583,0.468869
2016-05-11,6,0.504067,125.9644,5.9700,83.4100,233,0.000000,0.715833,0.284167,10,169,0.597000,0.540620,0.493550
2015-11-30,9,0.354111,69.5692,4.7976,78.9070,194,0.009111,0.847889,0.143000,16,187,0.299850,0.358604,0.421963
2018-01-11,451,0.253919,12457.6365,1778.6837,9142.7195,41215,0.031820,0.869650,0.098519,4210,26336,0.422490,0.302260,0.347157
2017-04-16,94,0.142204,572.9289,-5.0911,981.3461,4170,0.010606,0.922202,0.067213,68,6512,-0.074869,0.137393,0.150698
2014-08-12,3,0.164633,22.2255,0.9878,25.1889,79,0.000000,0.954000,0.046000,12,121,0.082317,0.281335,0.208173
2019-10-14,131,0.290811,3088.7930,1254.4628,1685.5034,9900,0.037763,0.856168,0.106069,2046,4071,0.613129,0.311999,0.414027
2016-06-09,4,0.428675,37.4748,1.7616,45.3779,110,0.000000,0.802750,0.197250,5,116,0.352320,0.340680,0.391189
2014-08-07,3,0.000000,0.0000,0.0000,0.0000,61,0.000000,1.000000,0.000000,9,88,0.000000,0.000000,0.000000
2016-11-27,23,0.110013,126.1880,-0.0644,238.3496,689,0.023696,0.917826,0.058478,3,980,-0.021467,0.183147,0.243214

In [29]:
bitcoin_pivot[['count', 'compound', 'neg', 'neu', 'pos', 'retweets_count', 'likes_count', 'replies_count',\
               'compound_weighted_replies', 'compound_weighted_likes', 'compound_weighted_retweets']]\
.to_csv("../data/bitcoin_daily_tweets.csv")

KeyError: "['date'] not in index"