In [85]:
import pandas as pd
import os
import numpy as np

In [3]:
os.chdir('/Users/ianjeong/Desktop/ML/great_cappsby/crypto-currency/data')

In [86]:
bitcoin = pd.read_csv('bitcoin_daily.csv')

In [88]:
# find daily change in closing price
bitcoin['Daily_Change'] = bitcoin['Close'] - bitcoin['Open']

In [96]:
def expo_moving_average(df, period):
    '''
    Calculate the exponential moving average.
    
    Input:
        df: a pandas dataframe
        period (int): time period
    Returns:
        rv: a pd series of exponential moving averages
    '''
    col_name = f'EMA_{period}' 
    rv = pd.Series([None] * df.shape[0])
    weight_0 = 2 / (period + 1) 
    weight_1 = 1 - weight_0
    for row in df.itertuples():
        if row.Index < period - 1:
            continue
        elif row.Index == period - 1:
            simple_average = df.loc[:period - 1, 'Close'].sum() / period
            #df.loc[row.Index, col_name] = simple_average
            rv[row.Index] = simple_average
        else:
            #ema = row.Close * weight_0 + df.loc[row.Index - 1, col_name] * weight_1
            ema = row.Close * weight_0 + rv[row.Index - 1] * weight_1
            #df.loc[row.Index, col_name] = ema
            rv[row.Index] = ema
    return rv

In [94]:
expo_moving_average(bitcoin, 12)
expo_moving_average(bitcoin, 26)

0               None
1               None
2               None
3               None
4               None
            ...
2742    40427.569083
2743    40570.623861
2744     40742.64854
2745    40981.040026
2746     41233.99742
Length: 2747, dtype: object

In [97]:
def moving_average_convergence_divergence(df):
    '''
    Find the moving average convergence divergence, which is equal to the
    difference between the 12-period exponential moving average and
    26-period exponential moving average.
    
    Modifies the dataframe in place.
    
    Input:
        df: a pd dataframe
    '''
    col_name = 'MACD'
    ema_12 = expo_moving_average(bitcoin, 12)
    ema_26 = expo_moving_average(bitcoin, 26)
    df['MACD'] = ema_12 - ema_26

In [53]:
# find the moving average converage divergence
bitcoin['MACD'] = bitcoin['EMA_12'] - bitcoin['EMA_26']

In [98]:
moving_average_convergence_divergence(bitcoin)

In [99]:
def proc(df, period):
    '''
    Calculate the price rate of change.
    
    Input:
        df: a pandas dataframe
        period (int): time period
    '''
    
    col_name = f'PROC_{period}'
    df[col_name] = None
    for row in df.itertuples():
        if row.Index < period:
            continue
        prev_idx = row.Index - period
        df.loc[row.Index, col_name] = (df.loc[row.Index, 'Close'] - df.loc[prev_idx, 'Close']) / df.loc[prev_idx, 'Close']

In [100]:
proc(bitcoin, 3)
proc(bitcoin, 5)
proc(bitcoin, 10)

In [103]:
def williams_percentage_range(df):
    '''
    Find the Williams Percentage Range. Modifies the df in place. 
    
    Input:
        df: a pd dataframe
    '''
    col_name = 'wpr'
    df[col_name] = None
    for row in df.itertuples():
        if row.Index < 14:
            continue
        max_14 = df.loc[row.Index - 14:row.Index - 1, 'Close'].max()
        min_14 = df.loc[row.Index - 14:row.Index - 1, 'Close'].min()
        wpr = (max_14 - row.Close) / (max_14 - min_14) * -100
        df.loc[row.Index, col_name] = wpr

In [104]:
williams_percentage_range(bitcoin)

In [105]:
def stochastic_oscillator(df):
    '''
    Find the stochastic oscillator. Modifies the df in place.
    '''
    col_name = 'sto_os'
    df[col_name] = None
    for row in df.itertuples():
        if row.Index < 14:
            continue
        max_14 = df.loc[row.Index - 14:row.Index - 1, 'Close'].max()
        min_14 = df.loc[row.Index - 14:row.Index - 1, 'Close'].min()
        so = (row.Close - min_14) / (max_14 - min_14) * 100
        df.loc[row.Index, col_name] = so

In [106]:
stochastic_oscillator(bitcoin)

In [107]:
bitcoin.head(30)

,Date,Open,High,Low,Close,Adj Close,Volume,Daily_Change,MACD,PROC_3,PROC_5,PROC_10,wpr,sto_os
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800,-8.529999,NaN,None,None,None,None,None
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200,-32.419983,NaN,None,None,None,None,None
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700,-29.307007,NaN,None,None,None,None,None
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600,14.230988,NaN,-0.105896,None,None,None,None
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100,-9.263977,NaN,-0.06036,None,None,None,None
5,2014-09-22,399.100006,406.915985,397.130005,402.152008,402.152008,24127600,3.052002,NaN,0.018632,-0.12066,None,None,None
6,2014-09-23,402.092010,441.557007,396.196991,435.790985,435.790985,45099500,33.698975,NaN,0.065754,0.026743,None,None,None
7,2014-09-24,435.751007,436.112000,421.131989,423.204987,423.204987,30627700,-12.546020,NaN,0.06114,0.071959,None,None,None
8,2014-09-25,423.156006,423.519989,409.467987,411.574005,411.574005,26814400,-11.582001,NaN,0.023429,0.00653,None,None,None
9,2014-09-26,411.428986,414.937988,400.009003,404.424988,404.424988,21460800,-7.003998,NaN,-0.071975,0.014051,None,None,None
10,2014-09-27,403.556000,406.622986,397.372009,399.519989,399.519989,15029300,-4.036011,NaN,-0.055966,-0.006545,-0.126415,None,None
11,2014-09-28,399.471008,401.016998,374.332001,377.181000,377.181000,23613300,-22.290008,NaN,-0.083565,-0.134491,-0.111344,None,None
12,2014-09-29,376.928009,385.210999,372.239990,375.467010,375.467010,32497700,-1.460999,NaN,-0.071603,-0.112801,-0.048959,None,None
13,2014-09-30,376.088013,390.976990,373.442993,386.944000,386.944000,34707300,10.855987,NaN,-0.031478,-0.059843,-0.053705,None,None
14,2014-10-01,387.427002,391.378998,380.779999,383.614990,383.614990,26229400,-3.812012,NaN,0.017058,-0.051456,-0.038127,-90.047297,9.952703
15,2014-10-02,383.988007,385.497009,372.946014,375.071991,375.071991,21777700,-8.916016,NaN,-0.001052,-0.061193,-0.067338,-100.654829,-0.654829
16,2014-10-03,375.181000,377.695007,357.859009,359.511993,359.511993,30901200,-15.669007,NaN,-0.070894,-0.046845,-0.175036,-125.626245,-25.626245
17,2014-10-04,359.891998,364.487000,325.885986,328.865997,328.865997,47236500,-31.026001,NaN,-0.142719,-0.124115,-0.222916,-140.176194,-40.176194
18,2014-10-05,328.915985,341.800995,289.295990,320.510010,320.510010,83308096,-8.405975,NaN,-0.145471,-0.171689,-0.221258,-107.814812,-7.814812
19,2014-10-06,320.389008,345.134003,302.559998,330.079010,330.079010,79011800,9.690002,NaN,-0.081869,-0.139557,-0.183831,-91.699411,8.300589
20,2014-10-07,330.584015,339.247009,320.481995,336.187012,336.187012,49199900,5.602997,NaN,0.022261,-0.103673,-0.158523,-86.40105,13.59895
21,2014-10-08,336.115997,354.364014,327.187988,352.940002,352.940002,54736300,16.824005,NaN,0.101182,-0.01828,-0.064269,-68.421053,31.578947
22,2014-10-09,352.747986,382.726013,347.687012,365.026001,365.026001,83641104,12.278015,NaN,0.105875,0.109954,-0.027808,-51.115706,48.884294
23,2014-10-10,364.687012,375.066986,352.963013,361.562012,361.562012,43665700,-3.125000,NaN,0.075479,0.128083,-0.065596,-51.079053,48.920947
24,2014-10-11,361.362000,367.191010,355.950989,362.299011,362.299011,13345200,0.937011,NaN,0.026517,0.097613,-0.055566,-47.109211,52.890789
25,2014-10-12,362.605988,379.433014,356.144012,378.549011,378.549011,17552800,15.943023,-19.267392,0.037047,0.126007,0.00927,-12.636587,87.363413
26,2014-10-13,377.920990,397.226013,368.897003,390.414001,390.414001,35221400,12.493011,-15.70184,0.079798,0.106177,0.085955,5.223231,105.223231
27,2014-10-14,391.691986,411.697998,391.324005,400.869995,400.869995,38491500,9.178009,-11.895282,0.106462,0.098196,0.218946,14.95765,114.95765
28,2014-10-15,400.954987,402.226990,388.765991,394.773010,394.773010,25267100,-6.181977,-9.263747,0.042858,0.091854,0.231703,-7.587091,92.412909
29,2014-10-16,394.518005,398.807007,373.070007,382.556000,382.556000,26990000,-11.962005,-8.071009,-0.020127,0.055912,0.158983,-22.789943,77.210057

In [108]:
bitcoin.to_csv('bitcoin_daily_modified.csv')